## Importing Python libs

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import dash
from dash import dcc, html
from dash.dependencies import Input, Output

import plotly.io as pio
pio.renderers.default = 'browser'

## Loading the dataset

In [2]:
stock_df = pd.read_csv("../dataset/Stock_Market_Dataset.csv", index_col=0)
stock_df

,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,Platinum_Price,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
0,02-02-2024,2.079,NaN,72.28,NaN,3.8215,NaN,"43,194.70",42650.0,901.6,...,"5,89,498",10580.0,564.64,4030000.0,171.81,117220000.0,474.99,84710000.0,"2,053.70",NaN
1,01-02-2024,2.050,161340.0,73.82,577940.0,3.8535,NaN,"43,081.40",47690.0,922.3,...,"5,81,600",9780.0,567.51,3150000.0,159.28,66360000.0,394.78,25140000.0,"2,071.10",260920.0
2,31-01-2024,2.100,142860.0,75.85,344490.0,3.9060,NaN,"42,580.50",56480.0,932.6,...,"5,78,020",9720.0,564.11,4830000.0,155.20,49690000.0,390.14,20010000.0,"2,067.40",238370.0
3,30-01-2024,2.077,139750.0,77.82,347240.0,3.9110,NaN,"42,946.20",55130.0,931.7,...,"5,84,680",9750.0,562.85,6120000.0,159.00,42290000.0,400.06,18610000.0,"2,050.90",214590.0
4,29-01-2024,2.490,3590.0,76.78,331930.0,3.8790,NaN,"43,299.80",45230.0,938.3,...,"5,78,800",13850.0,575.79,6880000.0,161.26,42840000.0,401.02,17790000.0,"2,034.90",1780.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,08-02-2019,2.583,147880.0,52.72,621000.0,2.8140,270.0,"3,661.70",699230.0,802.2,...,"3,00,771",240.0,347.57,7560000.0,79.41,113150000.0,167.33,12560000.0,"1,318.50",150610.0
1239,07-02-2019,2.551,211790.0,52.64,749010.0,2.8320,320.0,"3,397.70",471360.0,800.8,...,"3,02,813",240.0,344.71,7860000.0,80.72,92530000.0,166.38,17520000.0,"1,314.20",166760.0
1240,06-02-2019,2.662,98330.0,54.01,606720.0,2.8400,100.0,"3,404.30",514210.0,807.1,...,"3,08,810",120.0,352.19,6720000.0,82.01,78800000.0,170.49,13280000.0,"1,314.40",137250.0
1241,05-02-2019,2.662,82250.0,53.66,609760.0,2.8205,90.0,"3,468.40",460950.0,821.35,...,"3,10,700",360.0,355.81,9050000.0,82.94,89060000.0,171.16,22560000.0,"1,319.20",129010.0
1242,04-02-2019,2.660,116490.0,54.56,622470.0,2.7975,490.0,"3,462.80",503920.0,822.5,...,"3,12,000",310.0,351.34,9050000.0,81.67,98580000.0,169.25,20040000.0,"1,319.30",159560.0

## Basic Analysis of Dataset

In [3]:
stock_df.columns

Index(['Date', 'Natural_Gas_Price', 'Natural_Gas_Vol.', 'Crude_oil_Price',
       'Crude_oil_Vol.', 'Copper_Price', 'Copper_Vol.', 'Bitcoin_Price',
       'Bitcoin_Vol.', 'Platinum_Price', 'Platinum_Vol.', 'Ethereum_Price',
       'Ethereum_Vol.', 'S&P_500_Price', 'Nasdaq_100_Price', 'Nasdaq_100_Vol.',
       'Apple_Price', 'Apple_Vol.', 'Tesla_Price', 'Tesla_Vol.',
       'Microsoft_Price', 'Microsoft_Vol.', 'Silver_Price', 'Silver_Vol.',
       'Google_Price', 'Google_Vol.', 'Nvidia_Price', 'Nvidia_Vol.',
       'Berkshire_Price', 'Berkshire_Vol.', 'Netflix_Price', 'Netflix_Vol.',
       'Amazon_Price', 'Amazon_Vol.', 'Meta_Price', 'Meta_Vol.', 'Gold_Price',
       'Gold_Vol.'],
      dtype='object')

In [4]:
print(f"Stock dataset size: {stock_df.shape}")

Stock dataset size: (1243, 38)

In [5]:
stock_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Natural_Gas_Price,1243.0,3.494714e+00,1.822540e+00,1.482000e+00,2.347500e+00,2.702000e+00,4.055500e+00,9.647000e+00
Natural_Gas_Vol.,1239.0,1.316241e+05,6.438514e+04,1.200000e+03,9.190000e+04,1.273700e+05,1.694600e+05,3.819700e+05
Crude_oil_Price,1243.0,6.757706e+01,2.046550e+01,-3.763000e+01,5.509500e+01,6.923000e+01,8.045500e+01,1.237000e+02
Crude_oil_Vol.,1220.0,3.989038e+05,2.161619e+05,1.702000e+04,2.835975e+05,3.668850e+05,5.072425e+05,1.770000e+06
Copper_Price,1243.0,3.541957e+00,7.028187e-01,2.100500e+00,2.858750e+00,3.666000e+00,4.137250e+00,4.937500e+00
Copper_Vol.,1206.0,3.540662e+04,3.841545e+04,1.000000e+01,3.700000e+02,1.018000e+04,6.834000e+04,1.760400e+05
Bitcoin_Vol.,1243.0,4.033918e+07,2.940889e+08,2.600000e+02,7.907500e+04,2.153100e+05,6.151050e+05,4.470000e+09
Platinum_Vol.,636.0,9.082516e+03,8.876539e+03,0.000000e+00,1.120000e+03,6.070000e+03,1.528750e+04,4.283000e+04
Ethereum_Vol.,1243.0,1.801563e+07,1.326933e+08,7.518000e+04,5.883600e+05,1.570000e+06,9.365000e+06,1.790000e+09
Nasdaq_100_Vol.,1242.0,2.238827e+08,8.246992e+07,5.047000e+07,1.715275e+08,2.116200e+08,2.559850e+08,9.825600e+08
Apple_Price,1243.0,1.255665e+02,4.611412e+01,4.236000e+01,7.950500e+01,1.367600e+02,1.629150e+02,1.981100e+02
Apple_Vol.,1243.0,9.981845e+07,5.208192e+07,2.404000e+07,6.599000e+07,8.749000e+07,1.170750e+08,4.268800e+08
Tesla_Price,1243.0,1.735904e+02,1.066881e+02,1.193000e+01,5.333500e+01,2.020700e+02,2.514700e+02,4.099700e+02
Tesla_Vol.,1243.0,1.341790e+08,8.509129e+07,2.940000e+07,8.136000e+07,1.095200e+08,1.578300e+08,9.140800e+08
Microsoft_Price,1243.0,2.412401e+02,7.342984e+01,1.052500e+02,1.825250e+02,2.453800e+02,2.971200e+02,4.112200e+02
Microsoft_Vol.,1243.0,2.920801e+07,1.236710e+07,8.990000e+06,2.153500e+07,2.610000e+07,3.317500e+07,9.707000e+07
Silver_Price,1243.0,2.158898e+01,3.859288e+00,1.177200e+01,1.799850e+01,2.275800e+01,2.451200e+01,2.941800e+01
Silver_Vol.,1196.0,6.769542e+04,3.807885e+04,0.000000e+00,4.815000e+04,6.294000e+04,7.910000e+04,3.552800e+05
Google_Price,1243.0,9.967083e+01,2.976689e+01,5.194000e+01,7.118500e+01,1.012400e+02,1.272050e+02,1.535100e+02
Google_Vol.,1243.0,3.351599e+07,1.507215e+07,9.310000e+06,2.410500e+07,2.973000e+07,3.735500e+07,1.331800e+08
Nvidia_Price,1243.0,1.872858e+02,1.346799e+02,3.345000e+01,7.390500e+01,1.515900e+02,2.421400e+02,6.616000e+02
Nvidia_Vol.,1243.0,4.560298e+07,1.869107e+07,9.790000e+06,3.245000e+07,4.279000e+07,5.511500e+07,1.534600e+08
Berkshire_Vol.,1243.0,2.426525e+03,2.660498e+03,8.000000e+01,3.450000e+02,1.510000e+03,3.225000e+03,1.385000e+04
Netflix_Price,1243.0,4.048395e+02,1.149895e+02,1.663700e+02,3.230100e+02,3.841500e+02,4.953650e+02,6.916900e+02
Netflix_Vol.,1243.0,7.057401e+06,6.384187e+06,1.140000e+06,3.990000e+06,5.610000e+06,7.910000e+06,1.333900e+08
Amazon_Price,1243.0,1.286832e+02,3.080863e+01,7.941000e+01,9.626000e+01,1.287300e+02,1.581100e+02,1.865700e+02
Amazon_Vol.,1243.0,7.413005e+07,3.245753e+07,1.763000e+07,5.264500e+07,6.520000e+07,8.674500e+07,3.113500e+08
Meta_Price,1243.0,2.397281e+02,7.101543e+01,8.891000e+01,1.833550e+02,2.244300e+02,3.016500e+02,4.749900e+02
Meta_Vol.,1243.0,2.325851e+07,1.555486e+07,5.470000e+06,1.478500e+07,1.934000e+07,2.711500e+07,2.304100e+08
Gold_Vol.,1241.0,2.111277e+05,1.150064e+05,0.000000e+00,1.522000e+05,1.979700e+05,2.579200e+05,8.134100e+05

## Null Information of Dataset

In [6]:
# Function to display columns with null percentages and their data types
def display_null_info(df, name):
    null_count = df.isnull().sum()
    null_percentage = (null_count / len(df)) * 100
    column_types = df.dtypes

    # Combine information into a DataFrame
    null_info = pd.DataFrame({
        'Null Count': null_count,
        'Null Percentage': null_percentage,
        'Data Type': column_types
    })

    # Filter to show only columns with null values
    null_info = null_info[null_info['Null Count'] > 0]

    print(f"{name} null information:\n")
    print(null_info.to_string())
    print("\n")

print("Stock data:")
display_null_info(stock_df, "Stock Data")

Stock data:
Stock Data null information:

                  Null Count  Null Percentage Data Type
Natural_Gas_Vol.           4         0.321802   float64
Crude_oil_Vol.            23         1.850362   float64
Copper_Vol.               37         2.976669   float64
Platinum_Vol.            607        48.833467   float64
Nasdaq_100_Vol.            1         0.080451   float64
Silver_Vol.               47         3.781175   float64
Gold_Vol.                  2         0.160901   float64

## Null Preprocessing

In [7]:
stock_df = stock_df.drop(columns=['Platinum_Vol.'])

In [8]:
columns_to_fill = ['Natural_Gas_Vol.', 'Crude_oil_Vol.', 'Copper_Vol.',
                   'Nasdaq_100_Vol.', 'Silver_Vol.', 'Gold_Vol.']

# Fill null values using forward fill, then backward fill as fallback
for col in columns_to_fill:
    stock_df[col] = stock_df[col].fillna(method='ffill').fillna(method='bfill')

C:\Users\kansa\AppData\Local\Temp\ipykernel_20400\1943719049.py:6: FutureWarning:

Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

## Duplicate Analysis

In [9]:
print(f'Duplicated data in training dataset(size): {stock_df[stock_df.duplicated()].shape}')

Duplicated data in training dataset(size): (0, 37)

## Preprocessing (Converting Object columns to Numerical columns)

In [10]:
# Convert Date column to datetime format
stock_df['Date'] = pd.to_datetime(stock_df['Date'], format='%d-%m-%Y')

# List of columns to clean (removing commas and converting to numeric)
columns_to_clean = ['Bitcoin_Price', 'Platinum_Price', 'Ethereum_Price', 
                    'S&P_500_Price', 'Nasdaq_100_Price', 'Berkshire_Price', 'Gold_Price']

# Remove commas and convert to numeric
for col in columns_to_clean:
    stock_df[col] = stock_df[col].str.replace(',', '').astype(float)

In [ ]:
numerical_columns = stock_df.select_dtypes(include=['number']).columns.tolist()
categorical_columns = stock_df.select_dtypes(include=['object', 'category']).columns.tolist()
print(f'Numerical Columns: {numerical_columns}')
print(100*'-')
print(f'Categorical Columns: {categorical_columns}')

Numerical Columns: ['Natural_Gas_Price', 'Natural_Gas_Vol.', 'Crude_oil_Price', 'Crude_oil_Vol.', 'Copper_Price', 'Copper_Vol.', 'Bitcoin_Price', 'Bitcoin_Vol.', 'Platinum_Price', 'Ethereum_Price', 'Ethereum_Vol.', 'S&P_500_Price', 'Nasdaq_100_Price', 'Nasdaq_100_Vol.', 'Apple_Price', 'Apple_Vol.', 'Tesla_Price', 'Tesla_Vol.', 'Microsoft_Price', 'Microsoft_Vol.', 'Silver_Price', 'Silver_Vol.', 'Google_Price', 'Google_Vol.', 'Nvidia_Price', 'Nvidia_Vol.', 'Berkshire_Price', 'Berkshire_Vol.', 'Netflix_Price', 'Netflix_Vol.', 'Amazon_Price', 'Amazon_Vol.', 'Meta_Price', 'Meta_Vol.', 'Gold_Price', 'Gold_Vol.']
----------------------------------------------------------------------------------------------------
Categorical Columns: []

## Univariate Analysis

In [12]:
no_cols = 3
num_rows = (len(numerical_columns) + no_cols - 1) // no_cols

# Create subplots
fig = make_subplots(rows=num_rows, cols=no_cols)

# Iterate through all columns and create histograms
for i, col in enumerate(numerical_columns, 1):
    
    # Create histogram for the column
    fig.add_trace(go.Histogram(x=stock_df[col], name=col),
                  row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1)

    # Add titles and labels
    fig.update_xaxes(title_text=f'{col}  - Skew: {round(stock_df[col].skew(), 2)} | Kurt: {round(stock_df[col].kurt(), 2)}', row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1)
    fig.update_yaxes(title_text=f'Count', row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1)

# Update layout
fig.update_layout(height=num_rows * 500, width=1500, showlegend=False, title_text="Histograms for Each Column")

# Show plot
fig.show()

## Timeline Analysis

In [13]:
# Define the number of columns per row for subplots
no_cols = 3
numerical_columns = stock_df.columns.drop('Date')  # Exclude the Date column
num_rows = (len(numerical_columns) + no_cols - 1) // no_cols  # Calculate the number of rows

# Generate a color palette using Plotly Express
color_palette = px.colors.sequential.Viridis  # Choose a gradient palette
colors = [color_palette[i % len(color_palette)] for i in range(len(numerical_columns))]

# Create subplots
fig = make_subplots(rows=num_rows, cols=no_cols, 
                    subplot_titles=[col for col in numerical_columns])

# Iterate through all numerical columns and create area charts
for i, (col, color) in enumerate(zip(numerical_columns, colors), 1):
    # Create area chart
    fig.add_trace(
        go.Scatter(
            x=stock_df['Date'], 
            y=stock_df[col], 
            mode='lines', 
            fill='tozeroy',  # Fill the area under the line
            line=dict(color=color), 
            name=col
        ),
        row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1
    )

    # Add titles and labels
    fig.update_xaxes(title_text='Date', row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1)
    fig.update_yaxes(title_text=col, row=(i-1) // no_cols + 1, col=(i-1) % no_cols + 1)

# Update layout
fig.update_layout(
    height=num_rows * 500, 
    width=1500, 
    showlegend=False, 
    title_text="Stock Market Analysis",
    title_x=0.5,  # Center the title
)

# Show plot
fig.show()

## Date Column Processing

In [14]:
# Aggregate data (daily, monthly, yearly)
stock_df['Year'] = stock_df['Date'].dt.year
stock_df['Month'] = stock_df['Date'].dt.to_period('M')
stock_df['Day'] = stock_df['Date'].dt.to_period('D')

# Group data for different aggregation levels
daily_data = stock_df.groupby('Day').mean().reset_index()
monthly_data = stock_df.groupby('Month').mean().reset_index()
yearly_data = stock_df.groupby('Year').mean().reset_index()

## Saving the dataframe to csv

In [16]:
stock_df.to_csv("../dataset/Stock_Market_Preprocessed_Dataset.csv", index=False)

## Extra

In [ ]:
# Initialize Dash app
app = dash.Dash(__name__)

# Define dropdown options
columns = stock_df.columns.drop('Date')
dropdown_options = [{'label': col, 'value': col} for col in columns]

In [ ]:
# App layout
app.layout = html.Div(style={'backgroundColor': 'black', 'color': 'white'}, children=[
    html.H1("Market Trends Analysis Dashboard", style={'textAlign': 'center', 'color': 'white'}),

    # Dropdown for selecting an asset
    html.Div([
        html.Label("Select Asset:", style={'color': 'white'}),
        dcc.Dropdown(
            id='asset-dropdown',
            options=dropdown_options,
            value='Bitcoin_Price',  # Default value
            style={'width': '50%'}
        )
    ], style={'textAlign': 'center', 'margin': '20px'}),

    # Radio buttons for aggregation level
    html.Div([
        html.Label("Aggregation Level:", style={'color': 'white'}),
        dcc.RadioItems(
            id='aggregation-level',
            options=[
                {'label': 'Daily', 'value': 'daily'},
                {'label': 'Monthly', 'value': 'monthly'},
                {'label': 'Yearly', 'value': 'yearly'}
            ],
            value='daily',  # Default value
            labelStyle={'display': 'inline-block', 'margin-right': '20px'}
        )
    ], style={'textAlign': 'center', 'margin': '20px'}),

    # Graph for displaying trends
    dcc.Graph(id='trend-graph', style={'height': '600px'}),
])

@app.callback(
    Output('trend-graph', 'figure'),
    [Input('asset-dropdown', 'value'),
     Input('aggregation-level', 'value')]
)
def update_graph(selected_asset, aggregation_level):
    # Select data based on aggregation level
    if aggregation_level == 'daily':
        filtered_data = daily_data
        x_axis = 'Day'
    elif aggregation_level == 'monthly':
        filtered_data = monthly_data
        x_axis = 'Month'
    else:
        filtered_data = yearly_data
        x_axis = 'Year'

    # Convert x-axis (Period) to string for JSON serialization
    filtered_data[x_axis] = filtered_data[x_axis].astype(str)

    # Create figure
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=filtered_data[x_axis],
        y=filtered_data[selected_asset],
        mode='lines+markers',
        line=dict(color='cyan'),
        name=selected_asset
    ))

    # Customize layout
    fig.update_layout(
        title=f"Trend of {selected_asset} ({aggregation_level.capitalize()})",
        xaxis_title="Date",
        yaxis_title=selected_asset,
        paper_bgcolor='black',
        plot_bgcolor='black',
        font=dict(color='white'),
        hovermode='x'
    )
    return fig


app.run_server(debug=True)

In [ ]:
from dash import Dash, dcc, html, Input, Output

# Ensure no "Period" objects by using datetime aggregation
daily_data = stock_df.set_index('Date').resample('D').mean().reset_index()
monthly_data = stock_df.set_index('Date').resample('M').mean().reset_index()
yearly_data = stock_df.set_index('Date').resample('Y').mean().reset_index()

# Initialize the Dash app
app = Dash(__name__)

# App layout
app.layout = html.Div(style={'backgroundColor': 'black', 'color': 'white'}, children=[
    html.H1("Market Trends Analysis Dashboard", style={'textAlign': 'center', 'color': 'white'}),
    html.Div([
        html.Label("Select Asset:", style={'color': 'white'}),
        dcc.Dropdown(
            id='asset-dropdown',
            options=[{'label': col, 'value': col} for col in stock_df.columns if col != 'Date'],
            value='Bitcoin_Price',  # Default
            style={'width': '50%'}
        )
    ], style={'textAlign': 'center', 'margin': '20px'}),
    html.Div([
        html.Label("Aggregation Level:", style={'color': 'white'}),
        dcc.RadioItems(
            id='aggregation-level',
            options=[
                {'label': 'Daily', 'value': 'daily'},
                {'label': 'Monthly', 'value': 'monthly'},
                {'label': 'Yearly', 'value': 'yearly'}
            ],
            value='daily',  # Default
            labelStyle={'display': 'inline-block', 'margin-right': '20px'}
        )
    ], style={'textAlign': 'center', 'margin': '20px'}),
    dcc.Graph(id='trend-graph', style={'height': '600px'}),
])

# Callback for interactivity
@app.callback(
    Output('trend-graph', 'figure'),
    [Input('asset-dropdown', 'value'), Input('aggregation-level', 'value')]
)
def update_graph(selected_asset, aggregation_level):
    if aggregation_level == 'daily':
        filtered_data = daily_data
    elif aggregation_level == 'monthly':
        filtered_data = monthly_data
    else:
        filtered_data = yearly_data

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=filtered_data['Date'],
        y=filtered_data[selected_asset],
        mode='lines+markers',
        line=dict(color='cyan'),
        name=selected_asset
    ))

    fig.update_layout(
        title=f"Trend of {selected_asset} ({aggregation_level.capitalize()})",
        xaxis_title="Date",
        yaxis_title=selected_asset,
        paper_bgcolor='black',
        plot_bgcolor='black',
        font=dict(color='white'),
        hovermode='x'
    )
    return fig

# Run the app
if __name__ == '__main__':
    app.run(debug=True)